name: 'Portainer GitOps Action'
description: 'Perform GitOps actions against a Portainer instance'
author: 'defung'

inputs:
  portainer-host:
    description: portainer host (include scheme, domain, and port)
    required: true
  portainer-api-key:
    description: portainer api key
    required: true
  action:
    description: Portainer action (valid values = ['list', 'upsert', 'delete'] )
    required: true
  endpoint-id:
    description: portainer endpoint ID
    required: true
  stack-name:
    description: name stack (required if action is one of ['upsert', 'delete'])
  repo-url:
    description: url of repo (required if action=upsert)
  repo-compose-file-path:
    description: path to compose file in repo (required if action=upsert)
  repo-username:
    description: username of repo
  repo-password:
    description: username of repo

outputs:
  stacks:
    description: JSON array of stacks, if action='list'

runs:
  using: node20
  main: dist/index.js
